"""
===============================================================================
LANGGRAPH CONCEPT 1: STATE, NODES, EDGES, AND THE BASIC GRAPH LIFECYCLE
===============================================================================

What is LangGraph?
-----------------
LangGraph is a library for building stateful, multi-actor applications with LLMs.
Unlike traditional linear chains (where step A strictly leads to B then C),
LangGraph models workflows as DIRECTED GRAPHS where:
  - NODES: Python functions that execute work (e.g., calling Groq LLM, tools).
  - EDGES: Control flow defining which node runs next (sequential or conditional).
  - STATE: A shared data dictionary that flows through every node.
  - START & END: Virtual entry and exit points for the graph.

In this lesson:
  1. Define a shared State schema using TypedDict.
  2. Implement Worker Nodes that read State and return partial updates.
  3. Wire nodes together with Edges (START -> node1 -> node2 -> END).
  4. Compile and execute the graph.
  5. Inspect graph structure via ASCII diagram.
===============================================================================
"""

from typing import TypedDict, Annotated, List
import operator
from langgraph.graph import StateGraph, START, END
from config import get_llm

# =============================================================================
# 1. DEFINE THE GRAPH STATE
# =============================================================================
# The State is the single source of truth across the graph.
# Every node receives the current state and returns updates to it.
#
# By default, a node's return value OVERWRITES that field in the state.
# However, using `Annotated[List[str], operator.add]`, LangGraph APPENDS new
# items to the list instead of replacing the entire list (this is a REDUCER).
class EssayWorkflowState(TypedDict):
    topic: str                                  # The user's input topic (read-only)
    draft: str                                  # The initial draft written by LLM
    critique: str                               # Constructive feedback on the draft
    final_essay: str                            # The polished essay after feedback
    step_history: Annotated[List[str], operator.add]  # Reducer: Appends log entries


# =============================================================================
# 2. DEFINE THE NODES (WORKER FUNCTIONS)
# =============================================================================
# A node is simply a Python function:
#   Input: Current State (dict)
#   Output: Dict containing ONLY the fields to update

def drafter_node(state: EssayWorkflowState) -> dict:
    """
    Node 1: Drafter.
    Generates a short, initial draft based on the topic.
    """
    print("\n--- [NODE 1: DRAFTER] Generating initial draft... ---")
    llm = get_llm(temperature=0.7)

    prompt = (
        f"You are an essay writer. Write a short, single-paragraph draft "
        f"explaining this topic: '{state['topic']}'."
    )
    response = llm.invoke(prompt)

    # Return only the fields we want to update.
    # 'draft' will be updated with the response.
    # 'step_history' will have 'Draft created' appended because of operator.add.
    return {
        "draft": response.content,
        "step_history": ["Draft created by Drafter Node"],
    }


def critic_node(state: EssayWorkflowState) -> dict:
    """
    Node 2: Critic.
    Reviews the draft and provides concise suggestions for improvement.
    """
    print("\n--- [NODE 2: CRITIC] Reviewing draft and providing feedback... ---")
    llm = get_llm(temperature=0.3)

    prompt = (
        f"You are a strict editor. Review the following draft on '{state['topic']}':\n"
        f"'{state['draft']}'\n\n"
        f"Provide 2 concise points of constructive criticism to improve it."
    )
    response = llm.invoke(prompt)

    return {
        "critique": response.content,
        "step_history": ["Critique generated by Critic Node"],
    }


def polisher_node(state: EssayWorkflowState) -> dict:
    """
    Node 3: Polisher.
    Refines the draft by incorporating the critique to produce the final essay.
    """
    print("\n--- [NODE 3: POLISHER] Refining draft into final output... ---")
    llm = get_llm(temperature=0.5)

    prompt = (
        f"You are a master essayist. Rewrite the original draft by incorporating "
        f"the critique.\n\n"
        f"Original Draft:\n{state['draft']}\n\n"
        f"Critique:\n{state['critique']}\n\n"
        f"Output only the polished, final short essay."
    )
    response = llm.invoke(prompt)

    return {
        "final_essay": response.content,
        "step_history": ["Polishing completed by Polisher Node"],
    }


# =============================================================================
# 3. BUILD THE GRAPH (WIRING NODES & EDGES)
# =============================================================================
def build_basic_graph():
    """
    Constructs and compiles the StateGraph.
    Flow:
      START -> drafter -> critic -> polisher -> END
    """
    # Initialize the builder with our State schema
    builder = StateGraph(EssayWorkflowState)

    # 1. Add nodes to the graph
    builder.add_node("drafter", drafter_node)
    builder.add_node("critic", critic_node)
    builder.add_node("polisher", polisher_node)

    # 2. Add edges to connect the nodes
    # START connects to the very first node that receives the user input
    builder.add_edge(START, "drafter")
    builder.add_edge("drafter", "critic")
    builder.add_edge("critic", "polisher")
    # polisher connects to END to conclude graph execution
    builder.add_edge("polisher", END)

    # 3. Compile the graph into an executable Runnable
    compiled_graph = builder.compile()
    return compiled_graph


# =============================================================================
# 4. EXECUTION AND INSPECTION
# =============================================================================
def main():
    print("=" * 70)
    print("LANGGRAPH LESSON 1: STATE, NODES & SEQUENTIAL EDGES")
    print("=" * 70)

    # Compile the graph
    graph = build_basic_graph()

    # Visualize graph structure in ASCII
    print("\n[GRAPH TOPOLOGY]:")
    try:
        print(graph.get_graph().draw_ascii())
    except Exception:
        print("START -> drafter -> critic -> polisher -> END")

    # Initial input state passed to START
    initial_state = {
        "topic": "Why would jp morgan wins in banking",
        "draft": "",
        "critique": "",
        "final_essay": "",
        "step_history": ["Workflow initialized"],
    }

    print(f"\nUser Input Topic: {initial_state['topic']}")
    print("Invoking graph...")

    # graph.invoke() executes the graph from START to END
    final_output = graph.invoke(initial_state)

    print("\n" + "=" * 70)
    print("WORKFLOW EXECUTION RESULTS")
    print("=" * 70)
    print(f"\n1. INITIAL DRAFT:\n{final_output['draft']}")
    print(f"\n2. CRITIQUE:\n{final_output['critique']}")
    print(f"\n3. FINAL POLISHED ESSAY:\n{final_output['final_essay']}")
    print(f"\n4. STEP HISTORY (Demonstrating Reducer operator.add):")
    for idx, step in enumerate(final_output["step_history"], 1):
        print(f"   [{idx}] {step}")


if __name__ == "__main__":
    main()
